ASP.NET Core/MyMobile/MyMobile/Controllers/AdministrationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyMobile.DAL.Data;
using MyMobile.DAL.Models.Identity;
using MyMobile.DAL.Models.ViewModels.Administration;
using MyMobile.DAL.Models.ViewModels.Pages;
using MyMobile.Service.AccountService;
using MyMobile.Service.AdministrationService;
using MyMobile.Service.CarAdService;

namespace MyMobile.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class AdministrationController : Controller
    {
        private RoleManager<AppRole> RoleManager { get; }// create custom user and role manager classes
        private UserManager<AppUser> UserManager { get; }//
        private readonly IListingService listingService;
        private readonly IUserService userService;

        public AdministrationController(RoleManager<AppRole> roleManager, UserManager<AppUser> userManager, IListingService listingService, IUserService userService)
        {
            this.RoleManager = roleManager;
            this.UserManager = userManager;
            this.listingService = listingService;
            this.userService = userService;
        }

        public IActionResult AdminPanel()
        {
            AdminPanelViewModel model = new AdminPanelViewModel();
            model.UsersCount = userService.GetUsersCount();
            return View(model);
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRoleStore(CreateRoleViewModel formData)
        {
            if (ModelState.IsValid)
            {
                AppRole role = new AppRole()
                {
                    Name = formData.RoleName
                };

                IdentityResult result = await RoleManager.CreateAsync(role);
            }

            return RedirectToAction("ListRoles", "Administration");
        }

        [HttpGet]
        public IActionResult ListRoles()
        {
            ListRolesViewModel model = new ListRolesViewModel();
            model.Roles = RoleManager.Roles.ToList();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(int id)
        {
            EditRoleViewModel model = new EditRoleViewModel();

            var role = RoleManager.Roles.Where(r => r.Id == id).FirstOrDefault();

            model.RoleId = role.Id;
            model.RoleName = role.Name;

            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditRoleStore(EditRoleViewModel formData)
        {
            if (ModelState.IsValid)
            {
                AppRole role = RoleManager.Roles.Where(x => x.Id == formData.RoleId).FirstOrDefault();
                role.Name = formData.RoleName;
                IdentityResult result = await RoleManager.UpdateAsync(role);
            }

            return RedirectToAction("ListRoles", "Administration");
        }

        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(int roleId)
        {
            ViewBag.RoleId = roleId;

            var role = await RoleManager.FindByIdAsync(roleId.ToString());

            if (role == null)
            {
                return Content("Role cannot be found");
            }

            var model = new List<UserRoleViewModel>();

            foreach (var user in UserManager.Users.ToList())
            {
                UserRoleViewModel userRoleViewModel = new UserRoleViewModel();

                userRoleViewModel.UserId = user.Id;
                userRoleViewModel.Username = user.UserName;

                bool isInRole = await UserManager.IsInRoleAsync(user, role.Name);

                if (isInRole)
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }

                model.Add(userRoleViewModel);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> formDataCollection, int roleId)
        {
            var role = RoleManager.Roles.Where(r => r.Id == roleId).FirstOrDefault();

            for (int i = 0; i < formDataCollection.Count; i++)
            {
                var user = UserManager.Users.Where(u => u.Id == formDataCollection[i].UserId).FirstOrDefault();

                IdentityResult result = null;

                if (formDataCollection[i].IsSelected && !await UserManager.IsInRoleAsync(user, role.Name))
                {
                    result = await UserManager.AddToRoleAsync(user, role.Name);
                }
                else if (!formDataCollection[i].IsSelected && await UserManager.IsInRoleAsync(user, role.Name))
                {
                    result = await UserManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < formDataCollection.Count - 1)
                    {
                        continue;
                    }
                    else
                    {
                        return RedirectToAction("EditRole", new { Id = roleId });
                    }
                }
            }

            return RedirectToAction("EditRole", new { Id = roleId });
        }

        public async Task<IActionResult> ListUsers()
        {   ///////////////////////////////////////////////////////////////////
            ListUsersViewModel model = new ListUsersViewModel();
            List<AppUser> users = this.userService.GetUsers();
            var userViewModel = users.Select(u => new UserViewModel()
            {
                Id = u.Id,
                Username = u.UserName,
                RoleName = string.Join(", ", userService.GetUserRoles(u.Id))//UserManager.GetRolesAsync(u).Result.ToArray())
            }).ToList();

            foreach (var user in userViewModel)
            {
                user.AdsCount = this.listingService.GetUserListings(user.Id).Count();//
            }

            model.Users = userViewModel;
            return View(model);
            ///////////////////////////////////////////////////////////////////
        }

        public IActionResult ListAds()
        {
            var model = this.listingService.LoadAllListings();
            return View(model);
        }

        public IActionResult ListPendingAds()
        { 
            var model = this.listingService.LoadPendingListings();
            return View(model);
        }
    }
}

ASP.NET Core/MyMobile/MyMobile/Controllers/ListingsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyMobile.DAL.Data;
using MyMobile.DAL.Models.Identity;
using MyMobile.DAL.Models.ViewModels.Create;
using MyMobile.DAL.Models.ViewModels.Listings;
using MyMobile.Service.AccountService;
using MyMobile.Service.CarAdService;

namespace MyMobile.Controllers
{
    public class ListingsController : Controller
    {
        private readonly IUserService userService;
        private readonly IListingService listingService;

        public ListingsController(IUserService userService, IListingService listingService)
        {
            this.userService = userService;
            this.listingService = listingService;
        }

        public IActionResult Create()
        {
            return View(this.listingService.LoadCreateForm());
        }
        public IActionResult Delete(int id)
        {
            this.listingService.Delete(id);
            return RedirectToAction("ListPendingAds", "Administration");
        }
        public IActionResult ListModelsByMakeId(int makeId)
        {
            return Json(this.listingService.ListModelsById(makeId));
        }
        public IActionResult ListTownsByRegionId(int regionId)
        {
            return Json(this.listingService.ListTownsById(regionId));
        }
        public IActionResult Store(StoreListingViewModel formData)
        {
            if (User.Identity.IsAuthenticated)
            {
                formData.userId = this.userService.GetUserId();
                this.listingService.Create(formData);
                return RedirectToAction("MyAds", "Account");
            }
            else
            {
                this.listingService.Create(formData);
            }
            //fix method if condition and redirection when adding new listing as logged user or as annon

            return RedirectToAction("Index","Home");
        }
        [Authorize]
        public IActionResult Edit(int id)
        {
            return View(this.listingService.LoadEditListingPage(id));
        }
        public IActionResult EditStore(int id, StoreListingViewModel formData)
        {
            this.listingService.Update(id, formData);
            return RedirectToAction("MyAds", "Account");
        }
        public IActionResult Search(QuickSearchStoreViewModel formData, int? page)
        {
            return View(this.listingService.LoadListings(formData, page));
        }
        public IActionResult Listing(int id)
        {
            return View(this.listingService.LoadListing(id));
        }
        [Authorize(Roles = "SuperAdmin")]
        public IActionResult PendingListing(int id)
        {
            return View(this.listingService.LoadPendingListing(id));
        }
        public IActionResult ApproveListing(int id)
        {
            this.listingService.Approve(id);
            return RedirectToAction("ListPendingAds", "Administration");
        }

        [Authorize]
        public IActionResult Promote(int id)
        {
            var model = this.listingService.LoadPromoPage(id);
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public IActionResult PromoteStore(int promoId, int listingId)
        {
            this.listingService.Promote(promoId, listingId);
            return RedirectToAction("MyAds", "Account");
        }
    }
}

ASP.NET Core/MyMobile/MyMobile/Views/Administration/AdminPanel.cshtml
@using MyMobile.DAL.Models.ViewModels.Administration
@model AdminPanelViewModel
<div>
    <a asp-action="ListUsers" asp-controller="Administration">Настройки на потребители</a>
</div>
<div>
    <a asp-action="ListRoles" asp-controller="Administration">Настройки на правата на потребителите</a>
</div>
<div>
    <a asp-action="ListAds" asp-controller="Administration">Настройки на обяви</a>
</div>
<div>
    <a asp-action="ListPendingAds" asp-controller="Administration">Изчакващи обяви</a>
</div>

ASP.NET Core/MyMobile/MyMobile/Views/Administration/CreateRole.cshtml
@using MyMobile.DAL.Models.ViewModels.Administration
@model CreateRoleViewModel

<h2>Create Role</h2>
<div>
    <form method="post" asp-controller="Administration" asp-action="CreateRoleStore">
        <label>Role Name:</label>
        <input type="text" name="RoleName"/>
        <input type="submit" value="Create"/>
    </form>
</div>

ASP.NET Core/MyMobile/MyMobile/Views/Administration/EditRole.cshtml
@using MyMobile.DAL.Models.ViewModels.Administration
@model EditRoleViewModel

<h1>Edit Role</h1>

<form method="post" asp-action="EditRole" asp-controller="Administration">
    <div>
        <label asp-for="RoleId"></label>
        <input asp-for="RoleId" readonly />
    </div>
    <div>
        <label asp-for="RoleName"></label>
        <input asp-for="RoleName" value="@Model.RoleName" />
    </div>
    <div>
        <button type="submit" asp-action="EditRoleStore" asp-controller="Administration" asp-route-id="@Model.RoleId">Update</button>
        <a asp-action="ListRoles" asp-controller="Administration">Cancel</a>
    </div>
</form>

<div>
    <h2>Users in this role</h2>
    <div>
        @if(Model.Users.Count != 0)
        {
            foreach(var user in Model.Users)
            {
                <div>@user</div>
            }
        }
        else
        {
            <p>None at the moment</p>
        }
    </div>
    <div>
        <a asp-action="EditUsersInRole" asp-controller="Administration" asp-route-roleId="@Model.RoleId">Add or remove users</a>
    </div>
</div>

ASP.NET Core/MyMobile/MyMobile/Views/Administration/EditUsersInRole.cshtml
@using MyMobile.DAL.Models.ViewModels.Administration
@model List<UserRoleViewModel>

@{
    var roleId = ViewBag.roleId;
}

<h1>Add or remove users in role</h1>

<div>
    <form method="post" asp-action="EditUsersInRole" asp-controller="Administration" asp-route-roleId="@ViewBag.roleId">
        <table>
            @if (Model.Any())
            {
                @for(int i = 0; i < Model.Count; i++)
                {
                    <tr>
                        <td>
                            <input type="readonly" asp-for="@Model[i].UserId" />
                        </td>
                        <td>
                            <input type="readonly" asp-for="@Model[i].Username" />
                        </td>
                        <td>
                            <input asp-for="@Model[i].IsSelected" />
                        </td>
                    </tr>
                }
            }
        </table>
        <div>
            <input type="submit" value="Update" />
            <a class="btn btn-primary" style="width:auto" asp-action="EditRole" asp-controller="Administration" asp-route-id="@ViewBag.roleId">Cancel</a>
        </div>
    </form>
</div>

ASP.NET Core/MyMobile/MyMobile/Views/Administration/ListAds.cshtml
@model MyMobile.DAL.Models.ViewModels.Listings.ListingsViewModel
<style>
    #ads {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

        #ads td, #ads th {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }

        #ads tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        #ads tr:hover {
            background-color: #ddd;
        }

        #ads th {
            padding-top: 12px;
            padding-bottom: 12px;
            background-color: #328fc5;
            color: white;
        }
</style>

<div>
    <table id="ads">
        <tr>
            <th>
                Id
            </th>
            <th>
                Име
            </th>
            <th>
                Потребител
            </th>
            <th>
                Действия
            </th>
        </tr>
        @foreach (var ad in @Model.CarAds)
        {
            <tr>
                <td>
                    @ad.Id
                </td>
                <td>
                    @ad.Name
                </td>
                <td>
                    @if (ad.AppUser != null)
                    {
                        @ad.AppUser.UserName
                    }
                </td>
                <td>
                    <a>Преглед</a>
                    <span> | </span>
                    <a>Изтриване</a>
                </td>
            </tr>
        }
    </table>
</div>

ASP.NET Core/MyMobile/MyMobile/Views/Administration/ListPendingAds.cshtml
@model MyMobile.DAL.Models.ViewModels.Listings.ListingsViewModel
<style>
    #ads {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

        #ads td, #ads th {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }

        #ads tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        #ads tr:hover {
            background-color: #ddd;
        }

        #ads th {
            padding-top: 12px;
            padding-bottom: 12px;
            background-color: #328fc5;
            color: white;
        }
</style>


<h2>Списък на обявите изчакващи одобрение</h2>

<div>
    <table id="ads">
        <tr>
            <th>
                Id
            </th>
            <th>
                Име
            </th>
            <th>
                Потребител
            </th>
            <th>
                Действия
            </th>
        </tr>
        @foreach (var ad in @Model.CarAds)
        {
            <tr>
                <td>
                    @ad.Id
                </td>
                <td>
                    @ad.Name
                </td>
                <td>
                    @if (ad.AppUser != null)
                    {
                        @ad.AppUser.UserName
                    }
                </td>
                <td>
                    <a asp-action="PendingListing" asp-controller="Listings" asp-route-id="@ad.Id">Преглед</a>
                    <span> | </span>
                    <a asp-action="ApproveListing" asp-controller="Listings" asp-route-id="@ad.Id">Одобри</a>
                    <span> | </span>
                    <a asp-action="Delete" asp-controller="Listings" asp-route-id="@ad.Id">Изтрий</a>
                </td>
            </tr>
        }
    </table>
</div>

ASP.NET Core/MyMobile/MyMobile/Views/Administration/ListRoles.cshtml
@using MyMobile.DAL.Models.ViewModels.Administration
@model ListRolesViewModel
<style>
        #roles {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        #roles td, #roles th {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }

        #roles tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        #roles tr:hover {
            background-color: #ddd;
        }

        #roles th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #04AA6D;
            color: white;
        }
</style>
<h2>List of roles</h2>
<a asp-action="CreateRole" asp-controller="Administration">Add role</a>
<table id="roles" class="roles-table">
    <tr>
        <td>
            Id
        </td>
        <td>
            RoleName
        </td>
        <td>
            Действия
        </td>
    </tr>
@foreach (var role in @Model.Roles)
{
    <tr>
        <td>
            @role.Id
        </td>
        <td>
            @role.Name
        </td>
        <td>
            <a asp-action="EditRole" asp-controller="Administration" asp-route-id="@role.Id">Edit</a>
            <span> | </span>
            <a asp-action="DeleteRole" asp-controller="Administration" asp-route-id="@role.Id">Delete</a>
        </td>
    </tr>
}
</table>

ASP.NET Core/MyMobile/MyMobile/Views/Administration/ListUsers.cshtml
@using MyMobile.DAL.Models.ViewModels.Administration
@model ListUsersViewModel
<style>
        #users {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        #users td, #users th {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }

        #users tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        #users tr:hover {
            background-color: #ddd;
        }

        #users th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #04AA6D;
            color: white;
        }

</style>
@{
    ViewBag.Title = "All Users";
}

<h1>Списък на потребителите</h1>
@if (@Model.Users.Any())
{
    <table id="users">
        <tr>
            <td>ID</td>
            <td>Username/Email</td>
            <td>Права</td>
            <td>Брой обяви</td>
            <td>Действия</td>
        </tr>
        @foreach (var user in Model.Users)
        {
            <tr>
                <td>
                    @user.Id
                </td>
                <td>
                    @user.Username
                </td>
                <td>
                    @user.RoleName
                </td>
                <td>
                    @user.AdsCount
                </td>
                <td>
                    <a href="">Настройки</a>
                    <span>|</span>
                    <a href="">Преглед</a>
                    <span>|</span>
                    <a href="">Изтриване</a>
                </td>
            </tr>
        }
    </table>
}
else
{
    <div>No users created yet</div>
    <div>
        <a asp-action="Register" asp-controller="Account">Add new User</a>
    </div>
}